---
# tasks file for kubernetes-cluster
- name: add Kubernetes packages
  include_vars: kube_packages.yml

- name: Repo 
  include_tasks: repo.yml

- name: System config
  include_tasks: system-config.yml

- name: Package 
  include_tasks: package.yml

- name: User 
  include_tasks: user.yml
