---
# tasks file for kubernetes-cluster
- name: add Kubernetes packages
  include_vars: kube_packages.yml

- name: Add overlay and br-netfilter
  template:
    src: templates/overlay-br-netfilter.j2
    dest: /etc/modules-load.d/containerd.conf

- name: Add bridge
  template:
    src: templates/bridge.j2
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: Modprobe overlay
  command: modprobe overlay
  
- name: Modprobe br_netfilter
  command: modprobe br_netfilter 

- name: Sysctl without rebbot
  command: sysctl --system

- name: Repo 
  include_tasks: repo.yml

- name: System config
  include_tasks: system-config.yml

- name: Package 
  include_tasks: package.yml

- name: User 
  include_tasks: user.yml
