---
# tasks file for kubernetes-cluster
- name: add Kubernetes packages
  include_vars: kube_packages.yml

- name: add modprobe vars
  include_vars: modprobe.yml

- name: Add /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: Repo 
  include_tasks: repo.yml

- name: System config
  include_tasks: system-config.yml

- name: Package 
  include_tasks: package.yml

- name: User 
  include_tasks: user.yml
