- name: Install containerd
  command: dnf install containerd.io --allowerasing

- name: Install all Kubernetes packages
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    disable_excludes: kubernetes
  loop: "{{ kube_package }}"

- name: create containerd /etc/
  file:
    state: directory
    path: /etc/containerd

- name: Containerd setup
  raw: containerd config default > /etc/containerd/config.toml

- name: crictl config
  template:
    src: templates/crictl-config.j2
    dest: /etc/crictl.yaml

- name: Start containerd and kubelet
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: 
    - containerd
    - kubelet