- name: disable selinux
  selinux:
    state: disabled

- name: Swap off
  command: swapoff -a

- name: Permanent swapp off
  raw: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

